### ISSUE TITLE
cbc mode not working

### ISSUE THREAD

**Issue by 7bug0110** [agorlov/javascript-blowfish#5]
Hi,
the CBC mode is not working, you missed the part where you need to take the n block cipher as the IV for the block n+1
I mark the two lines to add with the // MISSING PART comments in the following function
And thanks for the lib of course ! It saves me some time !

  encryptCBC: function(string, iv) {
    string = this.utf8Decode(string);
    var blocks = Math.ceil(string.length/8);
    var ivL, ivR, ivLivR;
    ivLivR = this.split64by32(iv);
    ivL = ivLivR[0];
    ivR = ivLivR[1];
    var encryptedString = "";
    for (var i = 0; i < blocks; i++) {
      var block = string.substr(i \* 8, 8);
      if (block.length < 8) {
        var count = 8 - block.length;
        while (0 < count--) {
          block += "\0";
        }
      }
      var xL, xR, xLxR;
      xLxR = this.split64by32(block);
      xL = xLxR[0];
      xR = xLxR[1];
      xL = this.xor(xL, ivL);
      xR = this.xor(xR, ivR);
      xLxR = this.encipher(xL, xR);
      xL = xLxR[0];
      xR = xLxR[1];
      encryptedString += this.num2block32(xL) + this.num2block32(xR);
      ivL = xL; // MISSING PART
      ivR = xR; // MISSING PART
    }

**Comment by thommcgrath** [comment]
This issue may be 2 years old, but it sure helped me. I thought my decrypt code was wrong.

**Comment by fedevegili** [comment]
Thank you! Really helped me :)

**Comment by agorlov** [comment]
Adrian Scheit:
> I played with your blowfish implementation in javascript. It is very good! But did you noticed that CBC mode is not working? You can test it in pluncer: http://plnkr.co/edit/PC3So0dCjFHnxqFKMIKz?p=preview
Do you know why?
