### ISSUE TITLE
package.json

### ISSUE THREAD

**Issue by thesunlover** [agorlov/javascript-blowfish#7]
Hello there, :)

it would be great if you add a simple package.json file for npm install option

Thanks for the tool

**Comment by egoroof** [comment]
Looks like this lib is abandoned. Take a look at https://github.com/egoroof/blowfish which is published to npm.

**Comment by agorlov** [comment]
@thesunlover
I came out of suspended animation. ;-)
Pull request is merged.
Thank you!
